---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-assets

outputs:
- name: app-info

run:
  path: git-assets/pipeline/scripts/app-info.sh
  
  