# Don't activate H2 in cloud profile
# spring.datasource.platform=h2

## TEMP to work around self-signed certs on foundations
management:
  cloudfoundry:
    skip-ssl-validation: true
  endpoint:
    health:
      show-details: always

custom:
  s3-bucket:
    url: ${vcap.services.demo-s3-bucket.credentials.url:foo}
    accessKey: ${vcap.services.demo-s3-bucket.credentials.accessKey:foo}
    secretKey: ${vcap.services.demo-s3-bucket.credentials.secretKey:foo}
